"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import {
  Terminal,
  CheckSquare,
  Clock,
  Users,
  Target,
  AlertTriangle,
  BookOpen,
  Lightbulb,
  ArrowRight,
  Copy,
  X,
  Check,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"

interface OutcomeData {
  session: {
    id: string
    name: string
    agenda: string
    duration: number
    creator: string
    createdAt: string
  }
  completedTasks: string[]
  incompleteTasks: string[]
  decisions: string[]
  blockers: string[]
  endedAt: string
}

export default function OutcomePage() {
  const router = useRouter()
  const [outcomeData, setOutcomeData] = useState<OutcomeData | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const stored = sessionStorage.getItem("z3ro-outcome")
    if (stored) {
      setOutcomeData(JSON.parse(stored))
    } else {
      // No outcome data, redirect to setup
      router.push("/setup")
    }
  }, [router])

  const generateMarkdown = () => {
    if (!outcomeData) return ""

    const { session, completedTasks, incompleteTasks, decisions, blockers, endedAt } = outcomeData

    return `# Session Summary: ${session.name}

**Date:** ${new Date(session.createdAt).toLocaleDateString()}
**Duration:** ${session.duration} minutes
**Ended:** ${new Date(endedAt).toLocaleTimeString()}

## Agenda
${session.agenda}

## Completed Tasks (${completedTasks.length})
${completedTasks.map((t) => `- [x] ${t}`).join("\n") || "- None"}

## Incomplete Tasks (${incompleteTasks.length})
${incompleteTasks.map((t) => `- [ ] ${t}`).join("\n") || "- None"}

## Decisions (${decisions.length})
${decisions.map((d) => `- ${d}`).join("\n") || "- None"}

## Unresolved Blockers (${blockers.length})
${blockers.map((b) => `- ${b}`).join("\n") || "- None"}

## Recommendations
${completedTasks.length > 0 ? "- Good progress made. Consider scheduling a follow-up session." : "- Consider breaking tasks into smaller slices."}
${blockers.length > 0 ? `- ${blockers.length} blocker(s) require attention before next session.` : "- No blocking issues."}

---
*Generated by Z3RO Focus Session Manager*
`
  }

  const copyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const startNextSession = () => {
    // Pre-fill next session with proposed values
    const nextSessionData = {
      proposedGoal: outcomeData?.session.agenda || "",
      proposedDuration: outcomeData?.session.duration || 45,
      carryOverBlockers: outcomeData?.blockers || [],
    }
    sessionStorage.setItem("z3ro-next-seed", JSON.stringify(nextSessionData))
    router.push("/setup")
  }

  const archiveSession = () => {
    if (!outcomeData) return

    // Get existing archive or create new
    const existingArchive = localStorage.getItem("z3ro-archive")
    const archive = existingArchive ? JSON.parse(existingArchive) : []

    // Add current session to archive
    archive.unshift({
      ...outcomeData,
      archivedAt: new Date().toISOString(),
    })

    // Keep last 50 sessions
    localStorage.setItem("z3ro-archive", JSON.stringify(archive.slice(0, 50)))

    // Clear session data
    sessionStorage.removeItem("z3ro-session")
    sessionStorage.removeItem("z3ro-outcome")

    router.push("/archive")
  }

  if (!outcomeData) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: "#0D0D0D" }}>
        <div className="font-mono text-sm" style={{ color: "#52525B" }}>
          Loading outcome...
        </div>
      </div>
    )
  }

  const { session, completedTasks, incompleteTasks, decisions, blockers, endedAt } = outcomeData
  const totalTasks = completedTasks.length + incompleteTasks.length
  const completionRate = totalTasks > 0 ? Math.round((completedTasks.length / totalTasks) * 100) : 0

  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: "#0D0D0D" }}>
      {/* Header */}
      <header
        className="h-12 flex items-center justify-between px-4 border-b"
        style={{ backgroundColor: "#1A1A1A", borderColor: "#262626" }}
      >
        <div className="flex items-center gap-2">
          <Terminal className="h-4 w-4" style={{ color: "#3B82F6" }} />
          <span className="font-mono text-sm font-bold" style={{ color: "#FFFFFF" }}>
            Z3RO
          </span>
          <span className="font-mono text-xs" style={{ color: "#52525B" }}>
            / outcome
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className="font-mono text-xs" style={{ color: "#10B981" }}>
            SESSION ENDED
          </span>
        </div>
      </header>

      {/* Main content */}
      <main className="flex-1 flex flex-col">
        <ScrollArea className="flex-1">
          <div className="max-w-3xl mx-auto p-6 space-y-8">
            {/* Session header */}
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <CheckSquare className="h-5 w-5" style={{ color: "#10B981" }} />
                <h1 className="text-xl font-bold" style={{ color: "#FFFFFF" }}>
                  {session.name}
                </h1>
              </div>

              <div className="flex flex-wrap gap-4 text-sm">
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4" style={{ color: "#52525B" }} />
                  <span className="font-mono" style={{ color: "#A1A1AA" }}>
                    {session.duration}m session
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4" style={{ color: "#52525B" }} />
                  <span className="font-mono" style={{ color: "#A1A1AA" }}>
                    {session.creator}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="font-mono" style={{ color: "#52525B" }}>
                    Ended {new Date(endedAt).toLocaleTimeString()}
                  </span>
                </div>
              </div>
            </div>

            {/* Agenda */}
            <div className="p-4 rounded border-l-2" style={{ backgroundColor: "#1A1A1A", borderColor: "#3B82F6" }}>
              <div className="flex items-center gap-2 mb-2">
                <Target className="h-4 w-4" style={{ color: "#3B82F6" }} />
                <span className="font-mono text-xs uppercase" style={{ color: "#3B82F6" }}>
                  Agenda
                </span>
              </div>
              <p style={{ color: "#FFFFFF" }}>{session.agenda}</p>
            </div>

            {/* Stats overview */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-4 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                <div className="font-mono text-2xl font-bold" style={{ color: "#10B981" }}>
                  {completedTasks.length}
                </div>
                <div className="font-mono text-xs uppercase" style={{ color: "#52525B" }}>
                  Completed
                </div>
              </div>
              <div className="p-4 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                <div className="font-mono text-2xl font-bold" style={{ color: "#F59E0B" }}>
                  {incompleteTasks.length}
                </div>
                <div className="font-mono text-xs uppercase" style={{ color: "#52525B" }}>
                  Incomplete
                </div>
              </div>
              <div className="p-4 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                <div className="font-mono text-2xl font-bold" style={{ color: "#3B82F6" }}>
                  {decisions.length}
                </div>
                <div className="font-mono text-xs uppercase" style={{ color: "#52525B" }}>
                  Decisions
                </div>
              </div>
              <div className="p-4 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                <div className="font-mono text-2xl font-bold" style={{ color: "#EF4444" }}>
                  {blockers.length}
                </div>
                <div className="font-mono text-xs uppercase" style={{ color: "#52525B" }}>
                  Blockers
                </div>
              </div>
            </div>

            {/* Completion progress */}
            {totalTasks > 0 && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs uppercase" style={{ color: "#52525B" }}>
                    Task Completion
                  </span>
                  <span className="font-mono text-sm font-bold" style={{ color: "#FFFFFF" }}>
                    {completionRate}%
                  </span>
                </div>
                <div className="h-2 rounded-full overflow-hidden" style={{ backgroundColor: "#262626" }}>
                  <div
                    className="h-full rounded-full transition-all"
                    style={{
                      width: `${completionRate}%`,
                      backgroundColor: completionRate >= 80 ? "#10B981" : completionRate >= 50 ? "#F59E0B" : "#EF4444",
                    }}
                  />
                </div>
              </div>
            )}

            {/* Completed Tasks */}
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <CheckSquare className="h-4 w-4" style={{ color: "#10B981" }} />
                <h2 className="font-mono text-sm uppercase" style={{ color: "#10B981" }}>
                  Completed ({completedTasks.length})
                </h2>
              </div>
              {completedTasks.length > 0 ? (
                <div className="space-y-1">
                  {completedTasks.map((task, i) => (
                    <div key={i} className="flex items-start gap-2 p-2 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                      <Check className="h-4 w-4 shrink-0 mt-0.5" style={{ color: "#10B981" }} />
                      <span className="text-sm" style={{ color: "#A1A1AA" }}>
                        {task}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm font-mono" style={{ color: "#52525B" }}>
                  No tasks completed
                </p>
              )}
            </div>

            {/* Incomplete Tasks */}
            {incompleteTasks.length > 0 && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4" style={{ color: "#F59E0B" }} />
                  <h2 className="font-mono text-sm uppercase" style={{ color: "#F59E0B" }}>
                    Incomplete ({incompleteTasks.length})
                  </h2>
                </div>
                <div className="space-y-1">
                  {incompleteTasks.map((task, i) => (
                    <div key={i} className="flex items-start gap-2 p-2 rounded" style={{ backgroundColor: "#1A1A1A" }}>
                      <span className="text-sm shrink-0 mt-0.5" style={{ color: "#52525B" }}>
                        [ ]
                      </span>
                      <span className="text-sm" style={{ color: "#A1A1AA" }}>
                        {task}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Decisions */}
            {decisions.length > 0 && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <BookOpen className="h-4 w-4" style={{ color: "#3B82F6" }} />
                  <h2 className="font-mono text-sm uppercase" style={{ color: "#3B82F6" }}>
                    Decisions ({decisions.length})
                  </h2>
                </div>
                <div className="space-y-1">
                  {decisions.map((decision, i) => (
                    <div
                      key={i}
                      className="p-2 rounded border-l-2"
                      style={{ backgroundColor: "#1A1A1A", borderColor: "#3B82F6" }}
                    >
                      <span className="text-sm" style={{ color: "#A1A1AA" }}>
                        {decision}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Blockers */}
            {blockers.length > 0 && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4" style={{ color: "#EF4444" }} />
                  <h2 className="font-mono text-sm uppercase" style={{ color: "#EF4444" }}>
                    Unresolved Blockers ({blockers.length})
                  </h2>
                </div>
                <div className="space-y-1">
                  {blockers.map((blocker, i) => (
                    <div
                      key={i}
                      className="p-2 rounded border-l-2"
                      style={{ backgroundColor: "#1A1A1A", borderColor: "#EF4444" }}
                    >
                      <span className="text-sm" style={{ color: "#A1A1AA" }}>
                        {blocker}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recommendations */}
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <Lightbulb className="h-4 w-4" style={{ color: "#A1A1AA" }} />
                <h2 className="font-mono text-sm uppercase" style={{ color: "#A1A1AA" }}>
                  Recommendations
                </h2>
              </div>
              <div className="p-4 rounded space-y-2" style={{ backgroundColor: "#1A1A1A" }}>
                {completedTasks.length > 0 ? (
                  <p className="text-sm" style={{ color: "#A1A1AA" }}>
                    Good progress made on your agenda. Consider scheduling a follow-up session to continue momentum.
                  </p>
                ) : (
                  <p className="text-sm" style={{ color: "#A1A1AA" }}>
                    No tasks were completed. Consider breaking your work into smaller, more achievable slices next
                    session.
                  </p>
                )}
                {blockers.length > 0 && (
                  <p className="text-sm" style={{ color: "#F59E0B" }}>
                    {blockers.length} blocker(s) require attention before your next focus session.
                  </p>
                )}
              </div>
            </div>
          </div>
        </ScrollArea>

        {/* Actions footer */}
        <div className="border-t p-4" style={{ backgroundColor: "#1A1A1A", borderColor: "#262626" }}>
          <div className="max-w-3xl mx-auto flex flex-col sm:flex-row gap-3">
            <Button
              onClick={copyMarkdown}
              variant="outline"
              className="flex-1 h-11 font-mono border-[#262626] hover:bg-[#262626] bg-transparent"
              style={{ color: "#FFFFFF" }}
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4 mr-2" style={{ color: "#10B981" }} />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 mr-2" />
                  Copy Markdown
                </>
              )}
            </Button>
            <Button onClick={startNextSession} className="flex-1 h-11 font-mono bg-[#3B82F6] hover:bg-[#2563EB]">
              Start Next Session
              <ArrowRight className="h-4 w-4 ml-2" />
            </Button>
            <Button onClick={archiveSession} variant="ghost" className="h-11 font-mono" style={{ color: "#52525B" }}>
              <X className="h-4 w-4 mr-2" />
              Close
            </Button>
          </div>
        </div>
      </main>
    </div>
  )
}
